package progetto;

import java.io.Serializable;

public interface DistributedNodeListener<ID extends Comparable<ID> & Serializable> {
    /**
     * Method to notify a snapshot has been completed by the node.
     * @param node Reference to the node object that this event is generated by.
     *             Useful in case a class registers to multiple nodes with the same listener
     * @param snapshot The new snapshot.
     */
    void onShapshotCompleted(DistributedNode<ID> node, Snapshot<ID> snapshot);
}
